### ISSUE TITLE
Crash on v.1.0.5-beta10

### ISSUE THREAD

**Issue by MatthieuMoreau0** [convertigo/react-native-c8osdk#6] opened 2018-07-05 12:58 UTC
![image](https://user-images.githubusercontent.com/26383842/42324620-ea7be798-8063-11e8-8a0a-357afd7d31b1.png)

**Comment by CharlesGrimont** [comment] 2018-07-05 13:01
duplicate of convertigo/c8osdk-ios#3

**Closed as completed** 2018-07-05 13:08 UTC
Labels: invalid
